### ISSUE TITLE
Support user certificates

### ISSUE THREAD

**Issue by mcpherrinm** [square/sharkey#28]
I heard a bunch of feedback that user keys would be a desired feature, so we could support those.

I don't think we should try to build any sort of user verification into this service though.  There's just too many ways to do that.  We should provide an API for a trusted service to request certs on behalf of a user.

The usual thing for our services would be to define an ACL saying which x509 client certs are allowed to request user's ssh client certs, and it tells us what user it's for.
We could support the username in an X-Remote-User (or customizable) HTTP Header for use behind a reverse proxy that handles auth (eg, Sandstorm.io uses X-Sandstorm-User-Id, and SSO proxies may use other ones) and the user just makes requests through it.
Additionally, we might want to support usernames in the URL (because setting headers in other contexts is a little unusual)

**Comment by mbyczkowski** [comment]
Implemented in #82
