### ISSUE TITLE
sharkey-client: Only update files if they've changed

### ISSUE THREAD

**Issue by bensallen** [square/sharkey#41]
Sharkey-client should be made idempotent, and only update known_hosts and the signed certificate if Sharkey's version differs from whats on disk.

**Comment by mcpherrinm** [comment]
Is there a meaningful difference between checking if the files are the same and doing nothing, versus just overwriting it with the same content?

**Comment by bensallen** [comment]
Generally it seems like a more clean approach, i.e. don't change things that don't need changing. Meaningful is certainly debatable in this case however.

- Reduce the small amount of write I/O on every update. Replaced with a small amount of read I/O that will likely be cached. 
- Reduce the chance of the write getting corrupted, since there would be significantly lower number of times the file is written out. It is tough to quantify this, but I suspect chances are quite low.

**Comment by mcpherrinm** [comment]
We have sharkey update once daily: the amount of write I/O is so tiny it's meaningless, since we generally do actually update the file each time, since the cert will be signed with an extended expiration, and new hosts added to known_hosts.

I don't agree about cleanliness.  It's straightforward to just overwrite, with no chance of getting the checking logic wrong.  Less code is better code.

**Comment by bensallen** [comment]
Another issue is polluting logging with two sudo uses, when sudo wasn't necessarily needed. However at the once daily update period this doesn't make much practical difference either.

I was thinking of running the Sharkey update every 30 seconds to get known_hosts updated near real-time. However, even this amount of propagation lag would be problematic, so trusting the CA pub key is a better solution for my use-case (provisioning image based stateless clusters).

I'm fine with being closed if there's no interest in implementing either client based file comparison logic, or a last updated id / timestamp logic tracked by the server.

Ben

**Comment by mcpherrinm** [comment]
I think I'd like to leave it as-is for now, and see how we feel after a bit of operational expertise and if any issues crop up.  We can re-evaluate in a couple weeks.
